name: Python CICD Pipeline

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, staging, production]


    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3


      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      # Step 4: Set Environment Variables
      - name: Set Environment Variables for ${{ matrix.environment }}
        run: echo "ENVIRONMENT=${{ matrix.environment }}" >> $GITHUB_ENV


      # Step 5: Run Unit Tests
      - name: Run Unit Tests
        run: pytest tests/test_unit.py

      # Step 6: Run Integration Tests
      - name: Run Integration Tests
        run: pytest tests/test_integration.py        

      # Step 7: Run E2E Tests
      - name: Run E2E Tests
        run: pytest tests/test_e2e.py
